#ifndef __DEFAULTS_H__
#define __DEFAULTS_H__

#define DEFAULT_NUM_VECTORS 10
#define DEFAULT_VECTOR_SIZE 64

#define DEFAULT_ADDER_TREE_PAD_WIDTH 4
#define DEFAULT_ADD_PAD_WIDTH 2

#define DEFAULT_INPUT_EXP_WIDTH 5
#define DEFAULT_INPUT_MAN_WIDTH 10

#define DEFAULT_RESULT_EXP_WIDTH 8
#define DEFAULT_RESULT_MAN_WIDTH 23

#endif // __DEFAULTS_H__
